
# Instructions from:
# https://docs.docker.com/compose/wordpress/

# wordpress-backup part from:
# https://hub.docker.com/r/aveltens/wordpress-backup/
# https://github.com/angelo-v/wordpress-backup-quickstart/blob/master/docker-compose.yml

version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql-wordpress
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
#  backup:
#    image: aveltens/wordpress-backup
#    restart: always
#    volumes:
#     - ./backups:/backups
#     - wordpress_files:/var/www/html
#    depends_on:
#     - mysql
#    environment:
#     - "MYSQL_ENV_MYSQL_DATABASE=$MYSQL_DATABASE"
#     - "MYSQL_ENV_MYSQL_USER=$MYSQL_USER"
#     - "MYSQL_ENV_MYSQL_PASSWORD=$MYSQL_PASSWORD"
#     - "MYSQL_PORT_3306_TCP_PORT=3306"
volumes:
    db_data: {}
#    wordpress_files:
